// This file is auto-generated. Do not edit manually.
export const ZUN_LINKS: Record<number, string> = {
    4770: "https://open.spotify.com/track/0FI4IWcLsV1i4C2fqGf4fp", // 赤より紅い夢 (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4771: "https://open.spotify.com/track/3XekIrDD6GtLcnyGeaa3lZ", // ほおずきみたいに紅い魂 (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4772: "https://open.spotify.com/track/5l27uTmSawz0MycRttS5k3", // 妖魔夜行 (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4773: "https://open.spotify.com/track/4v5cKI7g6DGLYkBVVLbziL", // ルーネイトエルフ (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4774: "https://open.spotify.com/track/5QhPWGxjyZvVHoiIpmIJaK", // おてんば恋娘 (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4775: "https://open.spotify.com/track/7xtmnrhNW6KCUM5E7SVWTa", // 上海紅茶館　～ Chinese Tea (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4776: "https://open.spotify.com/track/14RAkBPAjPL9A25AgfrKGl", // 明治十七年の上海アリス (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4777: "https://open.spotify.com/track/17d0TIjAO7jPqd6nKAkGmg", // ヴワル魔法図書館 (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4778: "https://open.spotify.com/track/1k7OTUzrtpid6rtJ7C08Ll", // ラクトガール　～ 少女密室 (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4779: "https://open.spotify.com/track/5ggCJGIw4K7mpzhB8ODmQL", // メイドと血の懐中時計 (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4780: "https://open.spotify.com/track/2OJTYS4LNsZuxxjtOuRE2J", // 月時計　～ ルナ・ダイアル (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4781: "https://open.spotify.com/track/7uBZGn0OtiTbeN9WpM8v8x", // ツェペシュの幼き末裔 (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4782: "https://open.spotify.com/track/3a4zFuQWit4tzLJt8s6HJ9", // 亡き王女の為のセプテット (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4783: "https://open.spotify.com/track/6Bdv4I4OG6fzuYrstN6wlq", // 魔法少女達の百年祭 (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4784: "https://open.spotify.com/track/3gKMXBTtrPK3XDpejB0LgL", // U.N.オーエンは彼女なのか？ (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4785: "https://open.spotify.com/track/52vNt0ijsKFhYKKcKfNOk6", // 紅より儚い永遠 (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    4786: "https://open.spotify.com/track/2BRjWvPofUvffxVoBiMg2K", // 紅楼　～ Eastern Dream... (東方紅魔郷　～ the Embodiment of Scarlet Devil)
    448: "https://open.spotify.com/track/4d8NorPo25W7opRRdXrDMJ", // 蓬莱伝説 (蓬莱人形　～ Dolls in Pseudo Paradise)
    449: "https://open.spotify.com/track/1ZGR4MPB6xZnXXFIbGYRqa", // 二色蓮花蝶　～ Red and White (蓬莱人形　～ Dolls in Pseudo Paradise)
    450: "https://open.spotify.com/track/2Cbe4mgFCh4omcoa2XOi9D", // 桜花之恋塚　～ Japanese Flower (蓬莱人形　～ Dolls in Pseudo Paradise)
    451: "https://open.spotify.com/track/7fpvn7qBXQhrAMu5PheQWm", // 明治十七年の上海アリス (蓬莱人形　～ Dolls in Pseudo Paradise)
    452: "https://open.spotify.com/track/3iIpn9WluS6KijM9H989Xl", // 東方怪奇談 (蓬莱人形　～ Dolls in Pseudo Paradise)
    453: "https://open.spotify.com/track/5ARNlmuGnIHNeRunndByVr", // エニグマティクドール (蓬莱人形　～ Dolls in Pseudo Paradise)
    454: "https://open.spotify.com/track/1h4fp8g2gj356gcwIolv9d", // サーカスレヴァリエ (蓬莱人形　～ Dolls in Pseudo Paradise)
    455: "https://open.spotify.com/track/2wOQYgUU2FV57Yt5NDRk2k", // 人形の森 (蓬莱人形　～ Dolls in Pseudo Paradise)
    456: "https://open.spotify.com/track/6FU1Jd2C3ary9fxDE3CvVA", // Witch of Love Potion (蓬莱人形　～ Dolls in Pseudo Paradise)
    457: "https://open.spotify.com/track/6Qjk9yaK0tAwdvghcMP723", // リーインカーネイション (蓬莱人形　～ Dolls in Pseudo Paradise)
    458: "https://open.spotify.com/track/1kGpEbH5WPyrDkojJyVSuW", // U.N.オーエンは彼女なのか？(蓬莱人形 ver.) (蓬莱人形　～ Dolls in Pseudo Paradise)
    2824: "https://open.spotify.com/track/4zQHPNqsLt4zYC90fMVk6t", // 永遠の巫女 (蓬莱人形　～ Dolls in Pseudo Paradise)
    460: "https://open.spotify.com/track/1vcp0JiQuC1ynXNyxSjLjf", // 空飛ぶ巫女の不思議な毎日 (蓬莱人形　～ Dolls in Pseudo Paradise)
    107: "https://open.spotify.com/track/2zSH19wrgHQXsMBwgib3TY", // 妖々夢　～ Snow or Cherry Petal (東方妖々夢　～ Perfect Cherry Blossom)
    108: "https://open.spotify.com/track/1nosAIn3fisJKVj7Y6FfeG", // 無何有の郷　～ Deep Mountain (東方妖々夢　～ Perfect Cherry Blossom)
    109: "https://open.spotify.com/track/1PnUWuWljyIIVM2PraN4Dg", // クリスタライズシルバー (東方妖々夢　～ Perfect Cherry Blossom)
    110: "https://open.spotify.com/track/02VG339g6peAYY34bHnzll", // 遠野幻想物語 (東方妖々夢　～ Perfect Cherry Blossom)
    111: "https://open.spotify.com/track/23UEDfBkMl8Ejcj7pTasut", // ティアオイエツォン(withered leaf) (東方妖々夢　～ Perfect Cherry Blossom)
    112: "https://open.spotify.com/track/5aPorbwN3mrZW16PkBcXwj", // ブクレシュティの人形師 (東方妖々夢　～ Perfect Cherry Blossom)
    113: "https://open.spotify.com/track/4a7lEZMY9rcSQMb5ePrdcU", // 人形裁判　～ 人の形弄びし少女 (東方妖々夢　～ Perfect Cherry Blossom)
    114: "https://open.spotify.com/track/4I2JcWhvwqBfsWytvy52DH", // 天空の花の都 (東方妖々夢　～ Perfect Cherry Blossom)
    115: "https://open.spotify.com/track/7FeGwVTT3WfPlXx954bQn1", // 幽霊楽団　～ Phantom Ensemble (東方妖々夢　～ Perfect Cherry Blossom)
    116: "https://open.spotify.com/track/50Buo4wP1Rs1QzNfnwlPvP", // 東方妖々夢　～ Ancient Temple (東方妖々夢　～ Perfect Cherry Blossom)
    117: "https://open.spotify.com/track/7J4IpzG8PdrO935egcFf1Z", // 広有射怪鳥事　～ Till When? (東方妖々夢　～ Perfect Cherry Blossom)
    118: "https://open.spotify.com/track/4AqztYK8OeuRd7nvUaaqEy", // アルティメットトゥルース (東方妖々夢　～ Perfect Cherry Blossom)
    78: "https://open.spotify.com/track/6xLZogNignLKGFI0n6MPRF", // 幽雅に咲かせ、墨染の桜　～ Border of Life (東方妖々夢　～ Perfect Cherry Blossom)
    119: "https://open.spotify.com/track/6TVLiIW5scoyiWNhzjayt4", // ボーダーオブライフ (東方妖々夢　～ Perfect Cherry Blossom)
    120: "https://open.spotify.com/track/7DGLFJLinmlsWQ1yK4N19q", // 妖々跋扈 (東方妖々夢　～ Perfect Cherry Blossom)
    121: "https://open.spotify.com/track/2uJRJLCASJBwZFrzy4dCnz", // 少女幻葬　～ Necro-Fantasy (東方妖々夢　～ Perfect Cherry Blossom)
    122: "https://open.spotify.com/track/0Xk1ee5U8dLlwzIUFDoFiB", // 妖々跋扈　～ Who done it! (東方妖々夢　～ Perfect Cherry Blossom)
    123: "https://open.spotify.com/track/6pghDwM9AKpgoh6Wz8ITGx", // ネクロファンタジア (東方妖々夢　～ Perfect Cherry Blossom)
    124: "https://open.spotify.com/track/21zeDaJNTqsu6mJ5X9cEi1", // 春風の夢 (東方妖々夢　～ Perfect Cherry Blossom)
    125: "https://open.spotify.com/track/6nfXt0RsbnDUllSyViSibF", // さくらさくら　～ Japanize Dream... (東方妖々夢　～ Perfect Cherry Blossom)
    471: "https://open.spotify.com/track/29tzghjkhflsl3mKtC67hs", // 夜のデンデラ野を逝く (蓮台野夜行 ～ Ghostly Field Club)
    472: "https://open.spotify.com/track/7GhE5FLhsYgoxK8g0yaiIt", // 少女秘封倶楽部 (蓮台野夜行 ～ Ghostly Field Club)
    473: "https://open.spotify.com/track/4IclmD8wTHpkVI4Yj0T2mb", // 東方妖々夢　～ Ancient Temple (蓮台野夜行 ～ Ghostly Field Club)
    474: "https://open.spotify.com/track/65LxIsKBWHzUFoL6JfGCSH", // 古の冥界寺 (蓮台野夜行 ～ Ghostly Field Club)
    475: "https://open.spotify.com/track/3vozaUrdZ72x72l6N4tulQ", // 幻視の夜　～ Ghostly Eyes (蓮台野夜行 ～ Ghostly Field Club)
    476: "https://open.spotify.com/track/3VRbUUv6xWau01FtMO8e5e", // 魔術師メリー (蓮台野夜行 ～ Ghostly Field Club)
    477: "https://open.spotify.com/track/7lHFSZVYeLdDtqmx8sKpDp", // 月の妖鳥、化猫の幻 (蓮台野夜行 ～ Ghostly Field Club)
    478: "https://open.spotify.com/track/6U4plgziyBcqczUsR9TO8k", // 過去の花　～ Fairy of Flower (蓮台野夜行 ～ Ghostly Field Club)
    479: "https://open.spotify.com/track/5oB5IowvnSQU8qiBicgis5", // 魔法少女十字軍 (蓮台野夜行 ～ Ghostly Field Club)
    480: "https://open.spotify.com/track/5vqQ2hmz3UxKyA9NSUSZfG", // 少女幻葬　～ Necro-Fantasy (蓮台野夜行 ～ Ghostly Field Club)
    481: "https://open.spotify.com/track/6kjAp0PXNDfKK6R8DgfycI", // 幻想の永遠祭 (蓮台野夜行 ～ Ghostly Field Club)
    87: "https://open.spotify.com/track/7zOHGFRF9bZ0zZ0r8p8JOB", // 永夜抄　～ Eastern Night (東方永夜抄　～ Imperishable Night)
    88: "https://open.spotify.com/track/00FC1dw4gfWMvMx5CvJf6X", // 幻視の夜　～ Ghostly Eyes (東方永夜抄　～ Imperishable Night)
    89: "https://open.spotify.com/track/4ovSAyrQY7IoHX4rXsTFv9", // 蠢々秋月　～ Mooned Insect (東方永夜抄　～ Imperishable Night)
    90: "https://open.spotify.com/track/1mR7nMujTK4MHHDDhMXxcB", // 夜雀の歌声　～ Night Bird (東方永夜抄　～ Imperishable Night)
    91: "https://open.spotify.com/track/6ObsgTdALXk3abEoocdq1G", // もう歌しか聞こえない (東方永夜抄　～ Imperishable Night)
    92: "https://open.spotify.com/track/397WIaUl2Otr3Eo9A3hkzg", // 懐かしき東方の血　～ Old World (東方永夜抄　～ Imperishable Night)
    93: "https://open.spotify.com/track/1gb2kdCUPKesG6SPIuLDUL", // プレインエイジア (東方永夜抄　～ Imperishable Night)
    94: "https://open.spotify.com/track/6fzDCcooG0QWb1HjHzlY2f", // 永夜の報い　～ Imperishable Night (東方永夜抄　～ Imperishable Night)
    95: "https://open.spotify.com/track/25Ttk0eYaJ72nw6lqq0oXv", // 少女綺想曲　～ Dream Battle (東方永夜抄　～ Imperishable Night)
    77: "https://open.spotify.com/track/11StFFKObOLzD9OAF38Ulz", // 恋色マスタースパーク (東方永夜抄　～ Imperishable Night)
    96: "https://open.spotify.com/track/2OM0umD9wRHRsh6IfXZeMI", // シンデレラケージ　～ Kagome-Kagome (東方永夜抄　～ Imperishable Night)
    97: "https://open.spotify.com/track/7w7JILvKOC24f0TpkkmXgH", // 狂気の瞳　～ Invisible Full Moon (東方永夜抄　～ Imperishable Night)
    98: "https://open.spotify.com/track/2mQoVi1b3LvWmVVZXSF9EM", // ヴォヤージュ1969 (東方永夜抄　～ Imperishable Night)
    99: "https://open.spotify.com/track/3Jm2CA4iyaiowucnuX5UuT", // 千年幻想郷　～ History of the Moon (東方永夜抄　～ Imperishable Night)
    100: "https://open.spotify.com/track/2D2v2ifqav4zrZe6wMunyX", // 竹取飛翔　～ Lunatic Princess (東方永夜抄　～ Imperishable Night)
    101: "https://open.spotify.com/track/2euRPgQlys28MY9hUlg1IU", // ヴォヤージュ1970 (東方永夜抄　～ Imperishable Night)
    102: "https://open.spotify.com/track/3KnJ3ZXpzAtIQX7ZyTSGDJ", // エクステンドアッシュ　～ 蓬莱人 (東方永夜抄　～ Imperishable Night)
    103: "https://open.spotify.com/track/2zUZ0lkSOufYqVhf5D6VwM", // 月まで届け、不死の煙 (東方永夜抄　～ Imperishable Night)
    104: "https://open.spotify.com/track/5cEKrqhYsKPjnFbJgLDfg7", // 月見草 (東方永夜抄　～ Imperishable Night)
    105: "https://open.spotify.com/track/3H4tW1nwv3Do2qF1eHXYDe", // Eternal Dream　～ 幽玄の槭樹 (東方永夜抄　～ Imperishable Night)
    106: "https://open.spotify.com/track/3eqlPONKaQmRCXxT1bBo7G", // 東方妖怪小町 (東方永夜抄　～ Imperishable Night)
    589: "https://open.spotify.com/track/4qaeV22El6VNDQPVxVzshV", // 童祭　～ Innocent Treasures (夢違科学世紀　～ Changeability of Strange Dream)
    590: "https://open.spotify.com/track/5BQuspdEQR140Lg2Af0aAm", // 華胥の夢 (夢違科学世紀　～ Changeability of Strange Dream)
    591: "https://open.spotify.com/track/6XcWRBNKnpCoykTsXKgtPV", // 上海紅茶館　～ Chinese Tea (夢違科学世紀　～ Changeability of Strange Dream)
    592: "https://open.spotify.com/track/58HSQhBvNMjrD0xcsAoOeF", // ヴォヤージュ1969 (夢違科学世紀　～ Changeability of Strange Dream)
    593: "https://open.spotify.com/track/58VOCWtUvhS7BNwHpVqZo6", // 科学世紀の少年少女 (夢違科学世紀　～ Changeability of Strange Dream)
    594: "https://open.spotify.com/track/2ypwhWJOunvSRRNnb5IwsR", // 永夜の報い　～ Imperishable Night (夢違科学世紀　～ Changeability of Strange Dream)
    595: "https://open.spotify.com/track/53uu1EcWhlRvrSo8n8HVPy", // 夜が降りてくる　～ Evening Star (夢違科学世紀　～ Changeability of Strange Dream)
    596: "https://open.spotify.com/track/0kbGHHeudS0eSspg859lnL", // 人形裁判　～ 人の形弄びし少女 (夢違科学世紀　～ Changeability of Strange Dream)
    597: "https://open.spotify.com/track/45sCR0NYWyYd1DrBUTCk0v", // 夢と現の境界 (夢違科学世紀　～ Changeability of Strange Dream)
    598: "https://open.spotify.com/track/1B85mmZklvcHYB6PVGrwny", // 幻想機械　～ Phantom Factory (夢違科学世紀　～ Changeability of Strange Dream)
    599: "https://open.spotify.com/track/48J41OrmDKuExjxohjbo1B", // 幽玄の槭樹　～ Eternal Dream  (夢違科学世紀　～ Changeability of Strange Dream)
    394: "https://open.spotify.com/track/6VuMK5R1HZ2EOfcCJV4iLB", // 花映塚　～ Higan Retour (東方花映塚　～ Phantasmagoria of Flower View)
    395: "https://open.spotify.com/track/6OSr7FejJ43mTFZ3eq7qOs", // 春色小径　～ Colorful Path (東方花映塚　～ Phantasmagoria of Flower View)
    396: "https://open.spotify.com/track/2eNeYY0GGZXiUwt7S12bEf", // オリエンタルダークフライト (東方花映塚　～ Phantasmagoria of Flower View)
    397: "https://open.spotify.com/track/3n9o8d0A6HeqLlLW7Cv8WQ", // フラワリングナイト (東方花映塚　～ Phantasmagoria of Flower View)
    508: "https://open.spotify.com/track/6yTkDxjj1y9WMrr7Zjjf2s", // 東方妖々夢　～ Ancient Temple (東方花映塚　～ Phantasmagoria of Flower View)
    399: "https://open.spotify.com/track/06556ckYhO8EnSqXs7CPok", // 狂気の瞳　～ Invisible Full Moon (東方花映塚　～ Phantasmagoria of Flower View)
    400: "https://open.spotify.com/track/06vlLlW0AmsoE71FntAz64", // おてんば恋娘の冒険 (東方花映塚　～ Phantasmagoria of Flower View)
    401: "https://open.spotify.com/track/129EJ63kYiuSqLaR4n3GVr", // 幽霊楽団　～ Phantom Ensemble (東方花映塚　～ Phantasmagoria of Flower View)
    402: "https://open.spotify.com/track/3WzD6OH5WIArM3pnaSkhUm", // もう歌しか聞こえない　～ Flower Mix (東方花映塚　～ Phantasmagoria of Flower View)
    403: "https://open.spotify.com/track/4GQLi7Mg7egI4sULV3WAW9", // お宇佐さまの素い幡 (東方花映塚　～ Phantasmagoria of Flower View)
    404: "https://open.spotify.com/track/6ZUS2EtzyKuMgNCK2rUu7a", // 風神少女　(Short Version) (東方花映塚　～ Phantasmagoria of Flower View)
    405: "https://open.spotify.com/track/2PHT2r3C1WDcnAKrUGYjiQ", // ポイズンボディ　～ Forsaken Doll (東方花映塚　～ Phantasmagoria of Flower View)
    406: "https://open.spotify.com/track/0SnW379fsF1RZ3zdtaQv7u", // 今昔幻想郷　～ Flower Land (東方花映塚　～ Phantasmagoria of Flower View)
    407: "https://open.spotify.com/track/4sfHGyQjBwG5Qm0Yz2CGqS", // 彼岸帰航　～ Riverside View (東方花映塚　～ Phantasmagoria of Flower View)
    408: "https://open.spotify.com/track/05USCbCLiqpZc3NHHHeh8U", // 六十年目の東方裁判　～ Fate of Sixty Years (東方花映塚　～ Phantasmagoria of Flower View)
    409: "https://open.spotify.com/track/3h6AJP1kaClPIOJiNYEFzH", // 花の映る塚 (東方花映塚　～ Phantasmagoria of Flower View)
    410: "https://open.spotify.com/track/5Wqz1bi9Ghx9vdHnl5ObxP", // 此岸の塚 (東方花映塚　～ Phantasmagoria of Flower View)
    411: "https://open.spotify.com/track/3Z2ZXAMBa6BOQ2OsWwPnKd", // 花は幻想のままに (東方花映塚　～ Phantasmagoria of Flower View)
    412: "https://open.spotify.com/track/5ZrqxKmoZiaQH6oN8XbEjE", // 魂の花　～ Another Dream... (東方花映塚　～ Phantasmagoria of Flower View)
    6337: "https://open.spotify.com/track/5hQwinEnkoOqYfdtCCJKHA", // 幻想郷　～ Lotus Land Story (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1522: "https://open.spotify.com/track/1ZhyRcsSmSMkx6MsdZMo5t", // Witching Dream (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1523: "https://open.spotify.com/track/4YpWMfT0DwxtI2mqqq7n8U", // Selene's light (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1524: "https://open.spotify.com/track/2I8cBLO8eC2B5GptEHs6Ze", // 装飾戦　～ Decoration Battle (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1525: "https://open.spotify.com/track/6xNWIAhcXuegR9CuHL5zZ8", // Break the Sabbath (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1526: "https://open.spotify.com/track/2qFLy55PFiEYv20u13ohE1", // 紅響曲　～ Scarlet Phoneme (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1527: "https://open.spotify.com/track/6BOZISCnSSgm0N7sdPBckD", // Bad Apple!! (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1528: "https://open.spotify.com/track/3KOfyJXrltKbQuoeGILgvT", // 霊戦　～ Perdition crisis (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1529: "https://open.spotify.com/track/2VnXZCC9TCgzwLV3ixx3sF", // アリスマエステラ (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1530: "https://open.spotify.com/track/0rv38t6T0slhYIauzxhmP0", // 少女綺想曲　～ Capriccio (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1531: "https://open.spotify.com/track/2g3OglXOpTz3sRBSXu9BGG", // 星の器　～ Casket of Star (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1532: "https://open.spotify.com/track/575JhXxMEfd5AMYtelyNmT", // Lotus Love (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1533: "https://open.spotify.com/track/250ox4asyaTEKaZMOUf6ys", // 眠れる恐怖　～Sleeping Terror (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1534: "https://open.spotify.com/track/6ULGAymawbgWnAnquZqdUp", // Dream Land (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1535: "https://open.spotify.com/track/52cqvYbcAjvuhP2rS5L6bM", // 幽夢　～ Inanimate Dream (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1536: "https://open.spotify.com/track/24ONwgl1SHpNFiGmCqa0Bl", // 禁じざるをえない遊戯 (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1537: "https://open.spotify.com/track/7D09xx2NBKV8rPMDJd7dvK", // メイド幻想　～ Icemilk Magic (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1538: "https://open.spotify.com/track/1eLzzFIyjTjPsJG44dDnGc", // かわいい悪魔　～ Innocence (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1539: "https://open.spotify.com/track/3e50NnxlGd9AazIKvl9RfN", // Days (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1540: "https://open.spotify.com/track/1UTYrgihW5md5WqUbc01PF", // Peaceful (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1541: "https://open.spotify.com/track/5Hi2XK9TX7haPEmfXzwTuh", // Arcadian Dream (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1542: "https://open.spotify.com/track/2DtqD6WkEIF7V6yc54rjM0", // 幻想の住人 (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1543: "https://open.spotify.com/track/1QIRUw7iy8FyD6O1hYWqGm", // Lotus Road (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1544: "https://open.spotify.com/track/5FwQYlWhcnr87LCp64pDR1", // Dreamy pilot (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1545: "https://open.spotify.com/track/4Ti3O33Hk2dh3tvUYsssbj", // Incomplete Plot (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1546: "https://open.spotify.com/track/0tNyL2JmutWzpyf3uafVAo", // Border Land (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1547: "https://open.spotify.com/track/5pr4ecE2s9izG6uJqZesvo", // Magic Shop of Raspberry (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1548: "https://open.spotify.com/track/4LJ2zFHn8aA9S5dkieAZRQ", // Crescent Dream (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1454: "https://open.spotify.com/track/2hRXYDJog4bn5mfviUvsPm", // 装飾戦　～ Decoration Battle（未使用バージョン） (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    1455: "https://open.spotify.com/track/6asVyuOvyTSGxlEth8Txxh", // 幽夢　～ Inanimate Dream（未使用バージョン） (幺樂団の歴史１ Akyu's Untouched Score vol.1)
    606: "https://open.spotify.com/track/6GnBwIBQAdzFCEHVD2e8PV", // ヒロシゲ36号 ～ Neo Super-Express (卯酉東海道　～ Retrospective 53 minutes)
    607: "https://open.spotify.com/track/53rlL7uKOIfFyYACRLMkDA", // 53ミニッツの青い海 (卯酉東海道　～ Retrospective 53 minutes)
    608: "https://open.spotify.com/track/58UddhjriK9tIRn3b8Xt2H", // 竹取飛翔　～ Lunatic Princess (卯酉東海道　～ Retrospective 53 minutes)
    609: "https://open.spotify.com/track/3dEitSNtvqzuG7XllwrMV3", // 彼岸帰航　～ Riverside View (卯酉東海道　～ Retrospective 53 minutes)
    610: "https://open.spotify.com/track/45suVeLEfK55ibVEWcj9Wo", // 青木ヶ原の伝説 (卯酉東海道　～ Retrospective 53 minutes)
    611: "https://open.spotify.com/track/07Thx9u7PkrFyMlh6p3A2D", // お宇佐さまの素い幡 (卯酉東海道　～ Retrospective 53 minutes)
    612: "https://open.spotify.com/track/2bIRP2uOT2CzXUKOOFqxOP", // 月まで届け不死の煙 (卯酉東海道　～ Retrospective 53 minutes)
    613: "https://open.spotify.com/track/6hL6MbP0kj3mhCAI9ezuEc", // レトロスペクティブ京都 (卯酉東海道　～ Retrospective 53 minutes)
    614: "https://open.spotify.com/track/13sEx1E7pMouRwuHG9zImh", // ラクトガール　～ 少女密室 (Retrospective 53 minutes ver.) (卯酉東海道　～ Retrospective 53 minutes)
    615: "https://open.spotify.com/track/0xbDC09gn1lEIwAcdteSnp", // 千年幻想郷　～ History of the Moon (卯酉東海道　～ Retrospective 53 minutes)
    616: "https://open.spotify.com/track/7u7M7078YRZIoYownUPYa3", // 最も澄みわたる空と海 (卯酉東海道　～ Retrospective 53 minutes)
    617: "https://open.spotify.com/track/7EfuGONcnQwDrBo4DPeokm", // 月面ツアーへようこそ (大空魔術　～ Magical Astronomy)
    618: "https://open.spotify.com/track/5A5KLEWc2Ngr9IzKHgkEKr", // 天空のグリニッジ (大空魔術　～ Magical Astronomy)
    619: "https://open.spotify.com/track/6cfkh259M0gddrH5PNWx0b", // 東の国の眠らない夜 (大空魔術　～ Magical Astronomy)
    620: "https://open.spotify.com/track/0w1oqUIHlZfyQCz9DIhU0s", // 車椅子の未来宇宙 (大空魔術　～ Magical Astronomy)
    621: "https://open.spotify.com/track/78tlJLPd8e9OPtxwBlZV5I", // Demystify Feast (大空魔術　～ Magical Astronomy)
    622: "https://open.spotify.com/track/6QQOnGxrk2ERpSDPLIt5G8", // 衛星カフェテラス (大空魔術　～ Magical Astronomy)
    623: "https://open.spotify.com/track/7i93jUiyFhV77cfX3TpJhm", // G Free (大空魔術　～ Magical Astronomy)
    624: "https://open.spotify.com/track/1nX73f109WTBYVeD52iYmo", // 大空魔術　～ Magical Astronomy (大空魔術　～ Magical Astronomy)
    625: "https://open.spotify.com/track/08VjhcazH5oe0X1ZsvI6bl", // ネクロファンタジア (大空魔術　～ Magical Astronomy)
    626: "https://open.spotify.com/track/6GWCxqs08Jc95VfLd5c48H", // 向こう側の月 (大空魔術　～ Magical Astronomy)
    311: "https://open.spotify.com/track/5PdTpx0fTEPXoQpgBzavpg", // 怪綺談　～ Mystic Square (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    312: "https://open.spotify.com/track/48YccmRCQa7a7EtoE2NFIb", // Dream Express (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    313: "https://open.spotify.com/track/0Dp82nHxcUfjuLAChWYjGy", // 魔法陣　～ Magic Square (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    314: "https://open.spotify.com/track/5yVK2e3OZC8Ilnb949Yypz", // 夢想時空 (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    315: "https://open.spotify.com/track/3cKOWYD6Gy7X00eSHu3pzZ", // 霊天　～ Spiritual Heaven (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    316: "https://open.spotify.com/track/06nIXAuj4iAwnW4rph7Hmt", // Romantic Children (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    317: "https://open.spotify.com/track/2ilWjxk78w5dkzCQYHIeJY", // プラスチックマインド (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    318: "https://open.spotify.com/track/2YFlzwikt2HEvaSI6p3v4N", // メイプルワイズ (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    319: "https://open.spotify.com/track/3g9B7UMFBrC8GfT0UGaiSZ", // 禁断の魔法　～ Forbidden Magic (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    320: "https://open.spotify.com/track/2OFVxEAeuCX8faPndotxKj", // 真紅の少女　～ Crimson Dead!! (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    321: "https://open.spotify.com/track/7Bs4PUClh6LOdD0PafhoFi", // 裏切りの少女　～ Judas Kiss (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    322: "https://open.spotify.com/track/2l675JvDJAuOOSfn3ZqJCO", // the Last Judgement (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    323: "https://open.spotify.com/track/5IvjkjL3bLkQ6BBvgGaoDN", // 悲しき人形　～ Doll of Misery (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    324: "https://open.spotify.com/track/72fAxO5tAoO54oFc6lhUpp", // 世界の果て　～ World's End (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    325: "https://open.spotify.com/track/7EJD8Ao4S81hWKBX3ZAmRv", // 神話幻想　～ Infinite Being (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    326: "https://open.spotify.com/track/2F1HcsRFhkCpLPGRdgdZET", // 不思議の国のアリス (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    327: "https://open.spotify.com/track/4xZTXxQJATeVrpZuUNIHR5", // the Grimoire of Alice (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    328: "https://open.spotify.com/track/7MkDjzJPkmwyro5UAKb5X8", // 神社 (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    329: "https://open.spotify.com/track/0ow0s8V5s81la6jQ6yUSyb", // Endless (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    330: "https://open.spotify.com/track/333og5ePa1CPzbsoKZIMm4", // 久遠の楽園 (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    331: "https://open.spotify.com/track/3gysQguhle85Ot5tx4BPCJ", // Mystic Dream (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    333: "https://open.spotify.com/track/2wXaSvYpJDhqrybwuUVheC", // 魂の休らむ所 (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    332: "https://open.spotify.com/track/0TmeSvMAeZy43c05cnfKhT", // Peaceful Romancer (幺樂団の歴史２ Akyu's Untouched Score vol.2)
    1479: "https://open.spotify.com/track/6VurPY7qZq3iL80jNEguhd", // 東方封魔録　～浄土曼荼羅 (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    1480: "https://open.spotify.com/track/4YQCL0fkXS9TYkqcGiYgZL", // 博麗　～Eastern Wind (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    1481: "https://open.spotify.com/track/39UUeoLARm4uTIODxotR5d", // She's in a temper!! (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    1482: "https://open.spotify.com/track/2Rp428zvF3xALPsy5YXCxO", // End of Daylight (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    1483: "https://open.spotify.com/track/72UmMwPtsQ1CzAJdfDej7D", // やみのちから (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    1484: "https://open.spotify.com/track/5sH9gTAKf6jvMkAmOI4OCe", // 幻夢界 (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    1485: "https://open.spotify.com/track/6njkjiDFqssjkBfSqk83ij", // 死を賭して (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    1486: "https://open.spotify.com/track/6RgAhr0xS7hO57ChcF9qqw", // ひもろぎ、むらさきにもえ (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    1487: "https://open.spotify.com/track/792o4FHkPcdP44pDKT9wXR", // 恋色マジック (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    1488: "https://open.spotify.com/track/1ZO1ZdNEhq7xwS7xZvXE7m", // 東方封魔録　～幽幻乱舞 (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    1489: "https://open.spotify.com/track/6SASDc2ojHAxBxZKpeKQnE", // Complete Darkness (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    1490: "https://open.spotify.com/track/5bIgJqT1rgUoJ6lz9XRZf4", // エキストララブ (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    1491: "https://open.spotify.com/track/4yXyUi8soJWsJwW5Ifcey5", // 戦車むすめのみるゆめ (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    1492: "https://open.spotify.com/track/6cvHdbtYCz0OOnQi1ljLpw", // 遠野の森 (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    1493: "https://open.spotify.com/track/4P3MU8J1oQ1GmEWTYWfIzz", // 昔話わんだーらんど (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    256: "https://open.spotify.com/track/3bT0dj0pLNx5engZHX3wdC", // 博麗神社境内 (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    257: "https://open.spotify.com/track/2zzA3s8CEK9Z3rRIW6vZuD", // 陽落ちて (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    258: "https://open.spotify.com/track/36P0KlJx6xzNseRBnETRbB", // 封魔終演 (幺樂団の歴史３　～ Akyu's Untouched Score vol.3)
    573: "https://open.spotify.com/track/2gHHd1rvzKSGt1SuAvxgHt", // 封印されし神々 (東方風神録　～ Mountain of Faith)
    574: "https://open.spotify.com/track/2VZEfXIvY2xAkCfKuBIeAV", // 人恋し神様　～ Romantic Fall (東方風神録　～ Mountain of Faith)
    575: "https://open.spotify.com/track/2C7bTsT6gkO2wSB3gVQRHe", // 稲田姫様に叱られるから (東方風神録　～ Mountain of Faith)
    576: "https://open.spotify.com/track/4hkObMbLTnbPVk0pEKwXSK", // 厄神様の通り道　～ Dark Road (東方風神録　～ Mountain of Faith)
    577: "https://open.spotify.com/track/5zsvfT2kZQESqaivtw76Xg", // 運命のダークサイド (東方風神録　～ Mountain of Faith)
    578: "https://open.spotify.com/track/4rrL0f1iCU6GATz3Aou6L4", // 神々が恋した幻想郷 (東方風神録　～ Mountain of Faith)
    579: "https://open.spotify.com/track/7sPbjKgcBs0T8qqtm079Ih", // 芥川龍之介の河童　～ Candid Friend (東方風神録　～ Mountain of Faith)
    580: "https://open.spotify.com/track/78W4RXWKY9Gj2tAY5JvsEy", // フォールオブフォール　～ 秋めく滝 (東方風神録　～ Mountain of Faith)
    581: "https://open.spotify.com/track/6ZkSqa2UsCtBSZ52i0ZBG4", // 妖怪の山　～ Mysterious Mountain (東方風神録　～ Mountain of Faith)
    582: "https://open.spotify.com/track/5b57WFbHXp2UWb0FT0zIm0", // 少女が見た日本の原風景 (東方風神録　～ Mountain of Faith)
    75: "https://open.spotify.com/track/6J71kZMFD23vgaHIQWwkff", // 信仰は儚き人間の為に (東方風神録　～ Mountain of Faith)
    583: "https://open.spotify.com/track/2lMZhwgM7rusU419lU4KCD", // 御柱の墓場　～ Grave of Being (東方風神録　～ Mountain of Faith)
    584: "https://open.spotify.com/track/4TlvRJqiIRoXiIDhcbpyvy", // 神さびた古戦場　～ Suwa Foughten Field (東方風神録　～ Mountain of Faith)
    585: "https://open.spotify.com/track/6aAfdfPEte88bptpPIOeVs", // 明日ハレの日、ケの昨日 (東方風神録　～ Mountain of Faith)
    74: "https://open.spotify.com/track/68D3KVo5UkWaBIwvjY101y", // ネイティブフェイス (東方風神録　～ Mountain of Faith)
    586: "https://open.spotify.com/track/56XmtRm448E7qFApFOrHvG", // 麓の神社 (東方風神録　～ Mountain of Faith)
    587: "https://open.spotify.com/track/1iMgBbEZ1sdfoMDEwTzyKA", // 神は恵みの雨を降らす　～ Sylphid Dream (東方風神録　～ Mountain of Faith)
    588: "https://open.spotify.com/track/0PdGQnME1SX95WYsS40Aiu", // プレイヤーズスコア (東方風神録　～ Mountain of Faith)
    259: "https://open.spotify.com/track/6wAtCNBMeAJ5krswLDF1pE", // 夢は時空を越えて (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    260: "https://open.spotify.com/track/1FTAIO0O8RYqfRGTdenIQk", // Selection (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    261: "https://open.spotify.com/track/3fi35teitS8b6jE57ZHvph", // 東方妖恋談 (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    262: "https://open.spotify.com/track/3xtKXgatUdqKARUKFh4CJx", // Reincarnation (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    263: "https://open.spotify.com/track/0PHSguuxPfZ8RrDBEp3kac", // Dim. Dream (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    264: "https://open.spotify.com/track/4beszN0aKmAROwMFpdpLe6", // Tabula rasa　～ 空白少女 (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    265: "https://open.spotify.com/track/0efLhWFyOEApcHY70Wsagy", // Maniacal Princess (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    266: "https://open.spotify.com/track/71u01uxEO0p4QaYNPLHJ3t", // 夢消失　～ Lost Dream (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    267: "https://open.spotify.com/track/1AYgxC0StZvy0AT96OeuLV", // 夢幻遊戯　～ Dream War (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    278: "https://open.spotify.com/track/47OFSyV1vh1Hg7iw58QDHY", // 勝利デモ (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    268: "https://open.spotify.com/track/4hRHsGMFqsS710tYblMUtW", // 魔法決戦！ ～ Fight it out! (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    269: "https://open.spotify.com/track/1WD89ONgVjPYDQSwcCvUs0", // 非統一魔法世界論 (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    270: "https://open.spotify.com/track/0avlfAju1E71jDWjip34Hn", // Sailor of Time (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    271: "https://open.spotify.com/track/2w6ftkHobiW0eB9Gsq3BPu", // 魔法鐘愛 (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    272: "https://open.spotify.com/track/4i4cMYVuG8KOBLStvLiTCB", // Strawberry Crisis!! (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    273: "https://open.spotify.com/track/5wvKishVMbgXhblDNdbnvs", // 久遠の夢 (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    274: "https://open.spotify.com/track/4uDiPQsLylxigd5xEfXpWQ", // 東方の青い空 (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    275: "https://open.spotify.com/track/42UwKbOonhV3pep6pNC03i", // 永遠の満月 (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    276: "https://open.spotify.com/track/7ujwtL81Q3F45TMPGI4rLR", // Maple Dream... (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    279: "https://open.spotify.com/track/6d3PgsAk9kZxwjZIiGAeSt", // ゲームオーバー (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    277: "https://open.spotify.com/track/1xc2drCQ83lMTxMs8u7tMo", // 霊人の休日 (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    280: "https://open.spotify.com/track/39zvRatlISBiwW3xPLpYGK", // 時の風 (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    1519: "https://open.spotify.com/track/1KtIRBSSZ5LNklC29Pt11M", // スターボウドリーム (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    282: "https://open.spotify.com/track/2yOxssI7ihDqwHPg6I2E29", // Phantasmagoria (幺樂団の歴史４ Akyu's Untouched Score vol.4)
    1465: "https://open.spotify.com/track/0W8dyWmDix2SannNuNNvNM", // A Sacred Lot (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    459: "https://open.spotify.com/track/51uZxeGxZwUlVAHghewhvZ", // 永遠の巫女 (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    1467: "https://open.spotify.com/track/7Kc2fRen8kMvQjxRbPH5wr", // The Positive and Negative (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    1468: "https://open.spotify.com/track/5Ay0AK3OOEsQ8db5lg9B19", // Highly Responsive to Prayers (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    1469: "https://open.spotify.com/track/4q2eu6M5JmxGRKQhpbDp8u", // 東方怪奇談 (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    1470: "https://open.spotify.com/track/2A8e0aYeyhgdaqPQSBkKnx", // 天使伝説 (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    1471: "https://open.spotify.com/track/5IWlmRGUp9E8I4oJfHF3BZ", // Oriental Magician (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    1472: "https://open.spotify.com/track/1nQBUhMDbYnQ9DsCwvrPQP", // 破邪の小太刀 (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    1473: "https://open.spotify.com/track/3QehVnxwpZ9WLP7i6Lx8Xk", // 魔鏡 (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    1474: "https://open.spotify.com/track/0RklRHgNTR4ODkNJJLDBdU", // the Legend of KAGE (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    1475: "https://open.spotify.com/track/5fPdqvDCIDZhNt3OaJ3N8y", // いざ、倒れ逝くその時まで (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    2444: "https://open.spotify.com/track/2SoiQEi69qPnFp2Byg8QOJ", // Civilization of Magic (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    1477: "https://open.spotify.com/track/3o2wis8eZ0AGb3oQ2BRgiu", // 星幽天使 (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    1478: "https://open.spotify.com/track/0qq6saKnt7XhAs7I9Luhyx", // アイリス (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    2445: "https://open.spotify.com/track/6tWgDBwtc7n6x9f2mMlMxY", // テーマ・オブ・イースタンストーリー (幺樂団の歴史５　～ Akyu's Untouched Score vol.5)
    556: "https://open.spotify.com/track/0QD2lTEmm51BfXlAnlDwOh", // 地霊達の起床 (東方地霊殿　～ Subterranean Animism)
    557: "https://open.spotify.com/track/6yhIfsTIty8W4zwIHkwDMp", // 暗闇の風穴 (東方地霊殿　～ Subterranean Animism)
    558: "https://open.spotify.com/track/6h6mr1nqJPwLT4o9OHu0SF", // 封じられた妖怪　～ Lost Place (東方地霊殿　～ Subterranean Animism)
    559: "https://open.spotify.com/track/7JgCgpwudXWJOBj229Sq6X", // 渡る者の途絶えた橋 (東方地霊殿　～ Subterranean Animism)
    560: "https://open.spotify.com/track/2pSezqdOfisX8AJP9eepou", // 緑眼のジェラシー (東方地霊殿　～ Subterranean Animism)
    561: "https://open.spotify.com/track/0y2jX17Xa7Vd1h3muiNIAg", // 旧地獄街道を行く (東方地霊殿　～ Subterranean Animism)
    562: "https://open.spotify.com/track/5B7WmKPsFArdEdbMsVEcJM", // 華のさかづき大江山 (東方地霊殿　～ Subterranean Animism)
    563: "https://open.spotify.com/track/0cZaVReAXNcdvAlCbwqfB0", // ハートフェルトファンシー (東方地霊殿　～ Subterranean Animism)
    564: "https://open.spotify.com/track/5lQ57Wh2KxjDbkj8oZcirD", // 少女さとり　～ 3rd eye (東方地霊殿　～ Subterranean Animism)
    565: "https://open.spotify.com/track/2rVSbJihIy2RcWEkpeCQbD", // 廃獄ララバイ (東方地霊殿　～ Subterranean Animism)
    566: "https://open.spotify.com/track/4T11lhCr9o6kElvltBgEcP", // 死体旅行　～ Be of good cheer! (東方地霊殿　～ Subterranean Animism)
    567: "https://open.spotify.com/track/4mKSwy2g5V9HL8jiH7HdIV", // 業火マントル (東方地霊殿　～ Subterranean Animism)
    568: "https://open.spotify.com/track/2edYysJEOv00n69C4Tzhdd", // 霊知の太陽信仰　～ Nuclear Fusion (東方地霊殿　～ Subterranean Animism)
    569: "https://open.spotify.com/track/55BpjDfTQr7xz9c5IFksxb", // ラストリモート (東方地霊殿　～ Subterranean Animism)
    570: "https://open.spotify.com/track/6gWubHS6yS4ncea4MXSenX", // ハルトマンの妖怪少女 (東方地霊殿　～ Subterranean Animism)
    571: "https://open.spotify.com/track/0QEKowvhqjYi96lX36Bj0J", // 地霊達の帰宅 (東方地霊殿　～ Subterranean Animism)
    572: "https://open.spotify.com/track/4S4AG3V1HlUXi8OOIM0fRP", // エネルギー黎明　～ Future Dream... (東方地霊殿　～ Subterranean Animism)
    11: "https://open.spotify.com/track/0FxvbJXajCsOY7YcvxVoAw", // 青空の影 (東方星蓮船　～ Undefined Fantastic Object)
    12: "https://open.spotify.com/track/3NpK2nqo99xjIe8LLDm0AM", // 春の湊に (東方星蓮船　～ Undefined Fantastic Object)
    13: "https://open.spotify.com/track/2HmVMD3d4rNcLT4OrYMiab", // 小さな小さな賢将 (東方星蓮船　～ Undefined Fantastic Object)
    14: "https://open.spotify.com/track/5cuteJFSoBk9J4NWLS8Pus", // 閉ざせし雲の通い路 (東方星蓮船　～ Undefined Fantastic Object)
    15: "https://open.spotify.com/track/0usgNjSX1xN55sS71i52qH", // 万年置き傘にご注意を (東方星蓮船　～ Undefined Fantastic Object)
    16: "https://open.spotify.com/track/60Gd6NbyQG0kDQnp9VEmF2", // スカイルーイン (東方星蓮船　～ Undefined Fantastic Object)
    17: "https://open.spotify.com/track/3hm2ByvF9BhvRUoLFmVXV2", // 時代親父とハイカラ少女 (東方星蓮船　～ Undefined Fantastic Object)
    18: "https://open.spotify.com/track/0fFbuCsXMmn7QkyZ5po5Ie", // 幽霊客船の時空を越えた旅 (東方星蓮船　～ Undefined Fantastic Object)
    19: "https://open.spotify.com/track/5VeQgApj24nwW8DV6FBbsM", // キャプテン・ムラサ (東方星蓮船　～ Undefined Fantastic Object)
    20: "https://open.spotify.com/track/1kATUi8C5sMbqOG8LPZ4Sc", // 魔界地方都市エソテリア (東方星蓮船　～ Undefined Fantastic Object)
    21: "https://open.spotify.com/track/0fy7TLEnpU7NnnLErU20Ag", // 虎柄の毘沙門天 (東方星蓮船　～ Undefined Fantastic Object)
    22: "https://open.spotify.com/track/60OSHBJ5UpcPaN4nkwlqwT", // 法界の火 (東方星蓮船　～ Undefined Fantastic Object)
    23: "https://open.spotify.com/track/3dFbb72qBVTef0V9lulymQ", // 感情の摩天楼　～ Cosmic Mind (東方星蓮船　～ Undefined Fantastic Object)
    24: "https://open.spotify.com/track/1XV3HCZwRbaqaRcrXoNcr8", // 夜空のユーフォーロマンス (東方星蓮船　～ Undefined Fantastic Object)
    25: "https://open.spotify.com/track/6cGQca2qBRK5BlKxccufYS", // 平安のエイリアン (東方星蓮船　～ Undefined Fantastic Object)
    26: "https://open.spotify.com/track/2N5xfHOOwhuri7YXQ9A3dU", // 妖怪寺 (東方星蓮船　～ Undefined Fantastic Object)
    27: "https://open.spotify.com/track/3hJcWccI1NNLxIUf71sZzl", // 空の帰り道　～ Sky Dream (東方星蓮船　～ Undefined Fantastic Object)
    831: "https://open.spotify.com/track/01T0P4MxVcV6CecioOABPp", // 欲深き霊魂 (東方神霊廟　～ Ten Desires)
    832: "https://open.spotify.com/track/0QBHEvTH9cP3C69GmyLBRP", // 死霊の夜桜 (東方神霊廟　～ Ten Desires)
    833: "https://open.spotify.com/track/4sHeIRb5kqO22hurksk7A7", // ゴーストリード (東方神霊廟　～ Ten Desires)
    834: "https://open.spotify.com/track/60MrKPfvwXtwyDhctEx1EQ", // 妖怪寺へようこそ (東方神霊廟　～ Ten Desires)
    835: "https://open.spotify.com/track/16fOjVk7wfbjFKoJfPkovn", // 門前の妖怪小娘 (東方神霊廟　～ Ten Desires)
    836: "https://open.spotify.com/track/2T8JZg13rcJPgV5P705E5v", // 素敵な墓場で暮しましょ (東方神霊廟　～ Ten Desires)
    837: "https://open.spotify.com/track/4u1WJyARgiuK9SmsQhYeTR", // リジッドパラダイス (東方神霊廟　～ Ten Desires)
    838: "https://open.spotify.com/track/0tn2zBQjyFImHwrAhu19i4", // デザイアドライブ (東方神霊廟　～ Ten Desires)
    839: "https://open.spotify.com/track/12sAVWCLzyFdYwgjc8OqkM", // 古きユアンシェン (東方神霊廟　～ Ten Desires)
    840: "https://open.spotify.com/track/4baS2xoJpDU6e61dkVj46k", // 夢殿大祀廟 (東方神霊廟　～ Ten Desires)
    841: "https://open.spotify.com/track/6ZXI7qbptJyNFMmq38afmd", // 大神神話伝 (東方神霊廟　～ Ten Desires)
    842: "https://open.spotify.com/track/6exjN29O2OAik4AgUQlqUp", // 小さな欲望の星空 (東方神霊廟　～ Ten Desires)
    843: "https://open.spotify.com/track/5iRIv8TlNL5dPSR8uElAgx", // 聖徳伝説　～ True Administrator (東方神霊廟　～ Ten Desires)
    844: "https://open.spotify.com/track/3n9e892QK2Qfn8todWJCtF", // 妖怪裏参道 (東方神霊廟　～ Ten Desires)
    845: "https://open.spotify.com/track/1BJD1xhHPkHQau1LlPV8md", // 佐渡の二ッ岩 (東方神霊廟　～ Ten Desires)
    846: "https://open.spotify.com/track/63BkHZbcmTqsRUJXyvr8mI", // 神社の新しい風 (東方神霊廟　～ Ten Desires)
    847: "https://open.spotify.com/track/44RGa7StEW3HxRfIOL1Q73", // デザイアドリーム (東方神霊廟　～ Ten Desires)
    869: "https://open.spotify.com/track/3e26cfXj2VYjP7bTCHcEuq", // 衛星トリフネ (鳥船遺跡　～ Trojan Green Asteroid)
    870: "https://open.spotify.com/track/1JU4fF2axMjUJhXWElMtbb", // トロヤ群の密林 (鳥船遺跡　～ Trojan Green Asteroid)
    871: "https://open.spotify.com/track/2CJtypFJBX0XP23givPAmm", // デザイアドライブ (鳥船遺跡　～ Trojan Green Asteroid)
    872: "https://open.spotify.com/track/6uD2tqm7sd1Sh86fSShfQh", // フェアリー冒険譚 (鳥船遺跡　～ Trojan Green Asteroid)
    873: "https://open.spotify.com/track/63oqI9wmQ9ZnIUPQ9sffHC", // 天鳥船神社 (鳥船遺跡　～ Trojan Green Asteroid)
    874: "https://open.spotify.com/track/0WgVmjRT5RZqaxFRU0ggqv", // 夜空のユーフォーロマンス (鳥船遺跡　～ Trojan Green Asteroid)
    875: "https://open.spotify.com/track/7HPTMdv7Rbj1UGUWCQEpB1", // ハルトマンの妖怪少女 (鳥船遺跡　～ Trojan Green Asteroid)
    876: "https://open.spotify.com/track/1Q8Gnt0DcvfvBAd2K7GZKu", // 天鳥船神社の結界 (鳥船遺跡　～ Trojan Green Asteroid)
    877: "https://open.spotify.com/track/50i4UcvBdftUAAil2S7NeR", // 感情の摩天楼　～ Cosmic Mind (鳥船遺跡　～ Trojan Green Asteroid)
    878: "https://open.spotify.com/track/2FYC4gh5eoNfuWClxAVBlX", // 宇宙に浮かぶ幻想郷 (鳥船遺跡　～ Trojan Green Asteroid)
    879: "https://open.spotify.com/track/01QDwiDDakhHmaxG63PxfS", // 緑のサナトリウム (伊弉諾物質　～ Neo-traditionalism of Japan.)
    880: "https://open.spotify.com/track/1Qp6fzUIKNtrf3jgJFvzXv", // 牛に引かれて善光寺参り (伊弉諾物質　～ Neo-traditionalism of Japan.)
    881: "https://open.spotify.com/track/5AYkKEPojI1cFTeOeNDRU9", // ハートフェルトファンシー (伊弉諾物質　～ Neo-traditionalism of Japan.)
    882: "https://open.spotify.com/track/0ESt9a0OmzIJQpVa60Dl4X", // 六十年目の東方裁判　～ Fate of Sixty Years (伊弉諾物質　～ Neo-traditionalism of Japan.)
    883: "https://open.spotify.com/track/4aUiLlGJ3QqBQodM9axlvp", // アガルタの風 (伊弉諾物質　～ Neo-traditionalism of Japan.)
    884: "https://open.spotify.com/track/3zRgGYki0yfhiAa7zXlOrK", // イザナギオブジェクト (伊弉諾物質　～ Neo-traditionalism of Japan.)
    885: "https://open.spotify.com/track/1ITmYXkWl58NjRPwKZCUrz", // 妖怪裏参道 (伊弉諾物質　～ Neo-traditionalism of Japan.)
    886: "https://open.spotify.com/track/7eeB2oZ5IOAa5CX3nZDYfQ", // アンノウンX　～ Unfound Adventure (伊弉諾物質　～ Neo-traditionalism of Japan.)
    887: "https://open.spotify.com/track/4rLkYp1ybO7BIS6SWK18qP", // 日本中の不思議を集めて (伊弉諾物質　～ Neo-traditionalism of Japan.)
    888: "https://open.spotify.com/track/0LbCTMmAuYd6yD9UNA9oad", // 素敵な墓場で暮しましょ (伊弉諾物質　～ Neo-traditionalism of Japan.)
    929: "https://open.spotify.com/track/3sqUURAH1VO62FcHV5ZDUt", // 不思議なお祓い棒 (東方輝針城　～ Double Dealing Character)
    930: "https://open.spotify.com/track/07OgzaGV1Ofzm1ljwktqV7", // ミストレイク (東方輝針城　～ Double Dealing Character)
    931: "https://open.spotify.com/track/2Pk7MXZsPzQKwaS44iMoNj", // 秘境のマーメイド (東方輝針城　～ Double Dealing Character)
    932: "https://open.spotify.com/track/5o6LYwIBKH5ccWcb7Vs9zm", // 運河を行き交う人妖 (東方輝針城　～ Double Dealing Character)
    933: "https://open.spotify.com/track/2bCmcvstrvLkqQOIZ2ODf6", // 柳の下のデュラハン (東方輝針城　～ Double Dealing Character)
    934: "https://open.spotify.com/track/5nN333F9MqQgspxJYsxQLM", // 満月の竹林 (東方輝針城　～ Double Dealing Character)
    935: "https://open.spotify.com/track/043mzfQqVLMcGBpCwlO46Q", // 孤独なウェアウルフ (東方輝針城　～ Double Dealing Character)
    936: "https://open.spotify.com/track/11ZhdSNK8jIIhkZ9klfiWg", // マジカルストーム (東方輝針城　～ Double Dealing Character)
    937: "https://open.spotify.com/track/0AEwsm3W9EJKk0O8Hgxxqy", // 幻想浄瑠璃 (東方輝針城　～ Double Dealing Character)
    938: "https://open.spotify.com/track/4VEfex08N3kRFs8FGJQwLr", // 空中に沈む輝針城 (東方輝針城　～ Double Dealing Character)
    939: "https://open.spotify.com/track/2xGJTPi1Jz96y06jNlqH6m", // リバースイデオロギー (東方輝針城　～ Double Dealing Character)
    940: "https://open.spotify.com/track/647oFqSA7e0RFeIWkue9g0", // 針小棒大の天守閣 (東方輝針城　～ Double Dealing Character)
    941: "https://open.spotify.com/track/6tTFcsvSuSPrDPPlgBE3RH", // 輝く針の小人族　～ Little Princess (東方輝針城　～ Double Dealing Character)
    942: "https://open.spotify.com/track/2DE5biPut4IHfIrfrnpsLo", // 魔力の雷雲 (東方輝針城　～ Double Dealing Character)
    943: "https://open.spotify.com/track/0Dk9aSvxdb0uSvQI3cju3M", // 始原のビート　～ Pristine Beat (東方輝針城　～ Double Dealing Character)
    944: "https://open.spotify.com/track/2GcaQ81v5UnqkwtFfoxbSJ", // 小槌の魔力 (東方輝針城　～ Double Dealing Character)
    945: "https://open.spotify.com/track/6jqXYA0TeenS9lPS0TnP1x", // 不思議な不思議な道具達 (東方輝針城　～ Double Dealing Character)
    953: "https://open.spotify.com/track/35mwFPcJBM4A3xPaHHTCa4", // 反則の狼煙を上げろ (弾幕アマノジャク　～ Impossible Spell Card)
    954: "https://open.spotify.com/track/6bDfZqAB1yX2QBIG83biZQ", // 不可能弾幕には反則を (弾幕アマノジャク　～ Impossible Spell Card)
    955: "https://open.spotify.com/track/3yhu9JgF2OF9h26yX6NyqC", // ミッドナイトスペルカード (弾幕アマノジャク　～ Impossible Spell Card)
    956: "https://open.spotify.com/track/1qA9zKeJ3eLjIb6idrd9LU", // ロマンチック逃飛行 (弾幕アマノジャク　～ Impossible Spell Card)
    957: "https://open.spotify.com/track/1tmgmge7EikWUfZAbd7N39", // 永遠の三日天下 (弾幕アマノジャク　～ Impossible Spell Card)
    931: "https://open.spotify.com/track/4XBDCtfzfWq4ss66KQep3o", // 秘境のマーメイド (弾幕アマノジャク　～ Impossible Spell Card)
    939: "https://open.spotify.com/track/3o24WipoMNUoCrg5Moe5Xa", // リバースイデオロギー (弾幕アマノジャク　～ Impossible Spell Card)
    937: "https://open.spotify.com/track/2KoQ5tZmsKDY0GDMH5ghhn", // 幻想浄瑠璃 (弾幕アマノジャク　～ Impossible Spell Card)
    581: "https://open.spotify.com/track/2LXjaxBrE7502xaYDFzZU9", // 妖怪の山　～ Mysterious Mountain (弾幕アマノジャク　～ Impossible Spell Card)
    976: "https://open.spotify.com/track/58AZgR7jqCjl8lNdUByHRH", // 宇宙巫女現る (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    977: "https://open.spotify.com/track/4r1V1lrPEFqKdAIRLFSl0c", // 忘れがたき、よすがの緑 (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    978: "https://open.spotify.com/track/6fCxlXRmqxaFtPQhUo0YVo", // 兎は舞い降りた (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    979: "https://open.spotify.com/track/4cqS4ktuC2edicTTRT2jhF", // 湖は浄めの月光を映して (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    980: "https://open.spotify.com/track/1Qh7R665ueh0SCsv8jIeC8", // 九月のパンプキン (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    981: "https://open.spotify.com/track/3Z2uFoPD094JIPx0FTzfbY", // 宇宙を飛ぶ不思議な巫女 (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    982: "https://open.spotify.com/track/7Dlk6a8J2bnupLDAJIoYC9", // 永遠の春夢 (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    983: "https://open.spotify.com/track/3JYyDyrXbCedHofwbWP4Ei", // 凍り付いた永遠の都 (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    984: "https://open.spotify.com/track/2gjXD3DyqJxXhYioyuzgMk", // 逆転するホイールオブフォーチュン (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    985: "https://open.spotify.com/track/5uKkL0Rr3FRxrl5RZnjM1p", // 遥か38万キロのボヤージュ (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    986: "https://open.spotify.com/track/2rGC2VW3CDahDUn4siLjZ8", // 星条旗のピエロ (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    987: "https://open.spotify.com/track/0rxxsWh9Zx2kX3i5UGkRCd", // 故郷の星が映る海 (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    988: "https://open.spotify.com/track/2tUEFSQFhyTK9um49HoFad", // ピュアヒューリーズ　～ 心の在処 (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    989: "https://open.spotify.com/track/2eY6qmvEREEKfQQNywZ537", // 見た事も無い悪夢の世界 (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    990: "https://open.spotify.com/track/4u0xT30cEeGUK3I7OIeJMH", // パンデモニックプラネット (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    991: "https://open.spotify.com/track/5cDGJSoYU1x7AyxduzVheO", // 神社から見える月 (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    992: "https://open.spotify.com/track/0F7eYCWg0FmgVuDmViZD1Q", // 宇宙巫女帰還する (東方紺珠伝　～ Legacy of Lunatic Kingdom)
    1433: "https://open.spotify.com/track/7H21vZV61i1bhVxyQfvRwH", // 他愛も無い二人の博物誌 (燕石博物誌　～ Dr. Latency's Freak Report)
    1434: "https://open.spotify.com/track/6GWAOfHNbbKgE3uJInKTCK", // 凍り付いた永遠の都 (燕石博物誌　～ Dr. Latency's Freak Report)
    1435: "https://open.spotify.com/track/38WoRXsNsjHC8k80yiv0zh", // Dr.レイテンシーの眠れなくなる瞳 (燕石博物誌　～ Dr. Latency's Freak Report)
    1436: "https://open.spotify.com/track/0PGYj3OXiOe9sQNIBwiaEJ", // 九月のパンプキン (燕石博物誌　～ Dr. Latency's Freak Report)
    1437: "https://open.spotify.com/track/34h2HIB58k0ArtMNvorOky", // 須臾はプランクを超えて (燕石博物誌　～ Dr. Latency's Freak Report)
    1438: "https://open.spotify.com/track/2JD1v28L8qUYvVxNPKJXGv", // シュレディンガーの化猫 (燕石博物誌　～ Dr. Latency's Freak Report)
    1439: "https://open.spotify.com/track/744eilzApNc8n8f9wJXgdP", // 空中に沈む輝針城 (燕石博物誌　～ Dr. Latency's Freak Report)
    1440: "https://open.spotify.com/track/2OP7Ag46dVhshHkZpVNklW", // 禁忌の膜壁 (燕石博物誌　～ Dr. Latency's Freak Report)
    1441: "https://open.spotify.com/track/2nH9TUE10oZQai8g6WnerC", // 故郷の星が映る海 (燕石博物誌　～ Dr. Latency's Freak Report)
    1442: "https://open.spotify.com/track/0veHsNX7rqrokPeh6EPu2g", // ピュアヒューリーズ　～ 心の在処 (燕石博物誌　～ Dr. Latency's Freak Report)
    1443: "https://open.spotify.com/track/3YzX9HT1dDYAjyytEAd7bu", // 永遠の三日天下 (燕石博物誌　～ Dr. Latency's Freak Report)
    1444: "https://open.spotify.com/track/3cr9ptTt8Qmz5m0M0UC5xI", // バー・オールドアダム (旧約酒場　～ Dateless Bar \"Old Adam\")
    1445: "https://open.spotify.com/track/2KzQaaFnylPKN1MEvU5asu", // 燕石博物誌が連れてきた闇 (旧約酒場　～ Dateless Bar \"Old Adam\")
    1446: "https://open.spotify.com/track/3n7Dlbb815yrH8bh0CSiLo", // リバースイデオロギー (旧約酒場　～ Dateless Bar \"Old Adam\")
    1447: "https://open.spotify.com/track/6ueluzvw5pM2cWwV4JzP3H", // アウトサイダーカクテル (旧約酒場　～ Dateless Bar \"Old Adam\")
    1448: "https://open.spotify.com/track/4UaMMKVw6NDVnAZixms1gc", // 大神神話伝 (旧約酒場　～ Dateless Bar \"Old Adam\")
    1449: "https://open.spotify.com/track/54qQtWwrjwGld1zEhMSiOD", // パンデモニックプラネット (旧約酒場　～ Dateless Bar \"Old Adam\")
    1450: "https://open.spotify.com/track/5ThtFZlmNys5TWnA0nrtza", // 旧世界の冒険酒場 (旧約酒場　～ Dateless Bar \"Old Adam\")
    1451: "https://open.spotify.com/track/6Ti9XY6YKgYJq0QazLgIri", // 魔界地方都市エソテリア (旧約酒場　～ Dateless Bar \"Old Adam\")
    1452: "https://open.spotify.com/track/6qRiaEx6njtbaTBcH4MXaq", // 亡失のエモーション (旧約酒場　～ Dateless Bar \"Old Adam\")
    1453: "https://open.spotify.com/track/06NilLmUGra4GiZA1BiBLW", // 二日酔いの同床異夢 (旧約酒場　～ Dateless Bar \"Old Adam\")
    1018: "https://open.spotify.com/track/3IbLzAnnP0u8j3MKXIXy8t", // 桜舞い散る天空 (東方天空璋　～ Hidden Star in Four Seasons)
    1019: "https://open.spotify.com/track/3zRdqIQleWzcD5sXQtiNWI", // 希望の星は青霄に昇る (東方天空璋　～ Hidden Star in Four Seasons)
    1020: "https://open.spotify.com/track/4JGv9ZxLoJXKzNTIRdzziH", // 真夏の妖精の夢 (東方天空璋　～ Hidden Star in Four Seasons)
    1021: "https://open.spotify.com/track/3SYIEww36GpKLNi3e3cDoU", // 色無き風は妖怪の山に (東方天空璋　～ Hidden Star in Four Seasons)
    1022: "https://open.spotify.com/track/2rR7UDAGYC9MZblPtzgvC1", // 山奥のエンカウンター (東方天空璋　～ Hidden Star in Four Seasons)
    1023: "https://open.spotify.com/track/69XmIgxtPgt7mDZSiNy0ya", // 桜色の海を泳いで (東方天空璋　～ Hidden Star in Four Seasons)
    1024: "https://open.spotify.com/track/6tRyS9AuGD4uzI9zRP6nPy", // 一対の神獣 (東方天空璋　～ Hidden Star in Four Seasons)
    1025: "https://open.spotify.com/track/0zGE1XWZa4mwBUtFjhdE90", // 幻想のホワイトトラベラー (東方天空璋　～ Hidden Star in Four Seasons)
    1026: "https://open.spotify.com/track/62mm9UoRSUc1EDVWjRJvJk", // 魔法の笠地蔵 (東方天空璋　～ Hidden Star in Four Seasons)
    1027: "https://open.spotify.com/track/1Oxe0JnNasP3CP7PSKRT5B", // 禁断の扉の向こうは、この世かあの世か (東方天空璋　～ Hidden Star in Four Seasons)
    1028: "https://open.spotify.com/track/370AQXFtYDeE4ZRMBMntMt", // クレイジーバックダンサーズ (東方天空璋　～ Hidden Star in Four Seasons)
    1029: "https://open.spotify.com/track/1FTVrMysVsXpgGRYvxufJ7", // イントゥ・バックドア (東方天空璋　～ Hidden Star in Four Seasons)
    1030: "https://open.spotify.com/track/2NSZfmpaE94WsKbIOOB5Y5", // 秘匿されたフォーシーズンズ (東方天空璋　～ Hidden Star in Four Seasons)
    1031: "https://open.spotify.com/track/700UeXIXVNI9c3LIJ37EyC", // もうドアには入れない (東方天空璋　～ Hidden Star in Four Seasons)
    1032: "https://open.spotify.com/track/2uJPn03332z3v5vR1Gasue", // 秘神マターラ　～ Hidden Star in All Seasons. (東方天空璋　～ Hidden Star in Four Seasons)
    1033: "https://open.spotify.com/track/2DpkFQGjzeOujSxfGsnpib", // 不自然な自然 (東方天空璋　～ Hidden Star in Four Seasons)
    1034: "https://open.spotify.com/track/5fIOACoC7rKAAT9K1Ry7i0", // 白い旅人 (東方天空璋　～ Hidden Star in Four Seasons)
    4863: "https://open.spotify.com/track/4UGXveIikfl50XmyjJQba8", // 悪夢日記 (秘封ナイトメアダイアリー　〜 Violet Detector)
    4864: "https://open.spotify.com/track/2r5seEX4WYAoKjSyCdt4wb", // ルーシッドドリーマー (秘封ナイトメアダイアリー　〜 Violet Detector)
    4865: "https://open.spotify.com/track/18zP6SZrrQumHl4zA4Q0NZ", // ルナティックドリーマー (秘封ナイトメアダイアリー　〜 Violet Detector)
    4866: "https://open.spotify.com/track/0TPPRel1z7N6iIoVUFgSVI", // ナイトメアダイアリー (秘封ナイトメアダイアリー　〜 Violet Detector)
    4867: "https://open.spotify.com/track/7DrS7ggw460msQPoq2Wcg5", // バー・オールドアダム (秘封ナイトメアダイアリー　〜 Violet Detector)
    4868: "https://open.spotify.com/track/7q7yWRCcylHa1SAzbf8tHQ", // 燕石博物誌が連れてきた闇 (秘封ナイトメアダイアリー　〜 Violet Detector)
    4869: "https://open.spotify.com/track/2COFH6WxCBrbqFf46KdRRA", // 永遠の春夢 (秘封ナイトメアダイアリー　〜 Violet Detector)
    4870: "https://open.spotify.com/track/3iIqQF2TYdYqfdCfj1UdDQ", // 秘匿されたフォーシーズンズ (秘封ナイトメアダイアリー　〜 Violet Detector)
    12676: "https://open.spotify.com/track/4EjoX7HAeBuXVCliCuZswy", // 物言わぬ獣の霊 (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    12677: "https://open.spotify.com/track/3OnP7qPFhu5DScEVjM0Ebu", // 地蔵だけが知る哀嘆 (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    12678: "https://open.spotify.com/track/1HNpqXT1OpTgge773RD9si", // ジェリーストーン (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    12675: "https://open.spotify.com/track/5EtreckHozbUdRe3jd3wEs", // ロストリバー (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    12679: "https://open.spotify.com/track/0ZSsqcLD6qDr0eVnsSy84V", // 石の赤子と水中の牛 (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    12680: "https://open.spotify.com/track/42SMof6KHPByQG89iOBHct", // 不朽の曼珠沙華 (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    12681: "https://open.spotify.com/track/4RK7P609eZXrkAt9KGCgUv", // セラフィックチキン (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    14503: "https://open.spotify.com/track/4k1bthUpr7BvcO6ipWu7bm", // アンロケイテッドヘル (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    14504: "https://open.spotify.com/track/3iDJeLkcg3PgJ95HFtdSG4", // トータスドラゴン　～　幸運と不運 (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    14505: "https://open.spotify.com/track/1jFNSBmLY1GK5EIXOfmbcZ", // ビーストメトロポリス (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    14506: "https://open.spotify.com/track/77EfmhowRIQh3bFAV8nJqu", // セラミックスの杖刀人 (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    14507: "https://open.spotify.com/track/6fUJHSt3x1B4HXzrPB30Or", // エレクトリックヘリテージ (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    14508: "https://open.spotify.com/track/29tMxVxWxX0goue3X2QVuv", // 偶像に世界を委ねて　～ Idoratrize World (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    14509: "https://open.spotify.com/track/2IR3un909XVYdRehcc6c75", // 輝かしき弱肉強食の掟 (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    14510: "https://open.spotify.com/track/1rHShHdOabbtnH6ZM1JwaU", // 聖徳太子のペガサス　～ Dark Pegasus (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    14511: "https://open.spotify.com/track/3XNloaGCd7OrAJ05ikJwjF", // 畜生達の休息 (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    14512: "https://open.spotify.com/track/4e1vz6OMFWDsec97eapIHI", // 地下からの帰還 (東方鬼形獣 〜 Wily Beast and Weakest Creature.)
    28911: "https://open.spotify.com/track/6lqlDAV689geYIKQOg2FG3", // 虹の架かる幻想郷 (東方虹龍洞　～ Unconnected Marketeers.)
    28912: "https://open.spotify.com/track/76iir0CLq2yfCjAZD5oyh8", // 妖異達の通り雨 (東方虹龍洞　～ Unconnected Marketeers.)
    28913: "https://open.spotify.com/track/1z9L5qHS4TJGokr5AYNH4h", // 大吉キトゥン (東方虹龍洞　～ Unconnected Marketeers.)
    28914: "https://open.spotify.com/track/4wnx2Ov0393qEHzpQljJnp", // 深緑に隠された断崖 (東方虹龍洞　～ Unconnected Marketeers.)
    28915: "https://open.spotify.com/track/04WROieKUuBzP5k7Hy6dMy", // バンデットリィテクノロジー (東方虹龍洞　～ Unconnected Marketeers.)
    28916: "https://open.spotify.com/track/5CuzbBjlLwQkCQdMAQz9Jv", // 駒草咲くパーペチュアルスノー (東方虹龍洞　～ Unconnected Marketeers.)
    28917: "https://open.spotify.com/track/3PodJmEBU5fBcrdi50UsrG", // スモーキングドラゴン (東方虹龍洞　～ Unconnected Marketeers.)
    29356: "https://open.spotify.com/track/2qQkyIAMHOLaGv9iio8395", // 廃れゆく産業遺構 (東方虹龍洞　～ Unconnected Marketeers.)
    29357: "https://open.spotify.com/track/3MZOm8fnlb8h8x3Ns21vh9", // 神代鉱石 (東方虹龍洞　～ Unconnected Marketeers.)
    29358: "https://open.spotify.com/track/2dEMfMM86UJMbFibm0ZQoV", // 待ちわびた逢魔が時 (東方虹龍洞　～ Unconnected Marketeers.)
    29359: "https://open.spotify.com/track/2ubC5e3OFyVmwNrly7Urey", // 星降る天魔の山 (東方虹龍洞　～ Unconnected Marketeers.)
    29360: "https://open.spotify.com/track/0GY6dCeUm7nvplm67grewB", // ルナレインボー (東方虹龍洞　～ Unconnected Marketeers.)
    29361: "https://open.spotify.com/track/2cIno0SAR1zCVKwLo34spG", // あの賑やかな市場は今どこに　～ Immemorial Marketeers (東方虹龍洞　～ Unconnected Marketeers.)
    29362: "https://open.spotify.com/track/4wMVnFDOTfWyYS2MaScVMe", // 幻想の地下大線路網 (東方虹龍洞　～ Unconnected Marketeers.)
    29363: "https://open.spotify.com/track/2QeOdlBQqtks3Vgfdx27Tx", // 龍王殺しのプリンセス (東方虹龍洞　～ Unconnected Marketeers.)
    29364: "https://open.spotify.com/track/6EqQLlXo77cCPNmbAVUoQU", // 嵐の後の日曜日 (東方虹龍洞　～ Unconnected Marketeers.)
    29365: "https://open.spotify.com/track/4XoJfMfuWxeziosjB41lYe", // 虹色の世界 (東方虹龍洞　～ Unconnected Marketeers.)
    48801: "https://open.spotify.com/track/7kTSQDGyPM267dfZh5fheF", // コレクターの憂鬱な午後 (バレットフィリア達の闇市場　〜 100th Black Market.)
    48802: "https://open.spotify.com/track/2bZ6OrGAfhQMUq0WmcKDXi", // ワクワクする見慣れた幻想郷 (バレットフィリア達の闇市場　〜 100th Black Market.)
    48803: "https://open.spotify.com/track/1RGwqhXHO2l3W3IjOZ75Hj", // 妖怪フックオン (バレットフィリア達の闇市場　〜 100th Black Market.)
    48804: "https://open.spotify.com/track/4NNWp8KALlTKR7NK9ENP9f", // 闇市場は場所を選ばない (バレットフィリア達の闇市場　〜 100th Black Market.)
    48805: "https://open.spotify.com/track/1ZVhpZSgOjRHK9lHBo5nRD", // 弾幕を持て、パレッドフィリア達よ (バレットフィリア達の闇市場　〜 100th Black Market.)
    48806: "https://open.spotify.com/track/0mQOO13JMIMQ4Sx172KzH1", // 100回目のブラックマーケット (バレットフィリア達の闇市場　〜 100th Black Market.)
    4865: "https://open.spotify.com/track/6OPHXxLcwdtSM9UftCvL1t", // ルナティックドリーマー (バレットフィリア達の闇市場　〜 100th Black Market.)
    29360: "https://open.spotify.com/track/3KEd1cLZFYo1JozRK0MZuQ", // ルナレインボー (バレットフィリア達の闇市場　〜 100th Black Market.)
    29361: "https://open.spotify.com/track/3ILr8wWzfWzr81ssxO4xfZ", // あの賑やかな市場は今どこに　～ Immemorial Marketeers (バレットフィリア達の闇市場　〜 100th Black Market.)
    29365: "https://open.spotify.com/track/2LNLHULp8JMouJEYPsO7IX", // 虹色の世界 (バレットフィリア達の闇市場　〜 100th Black Market.)
    68791: "https://open.spotify.com/track/3mXapjfplbCdczIQuICV2b", // 獣の知性 (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    68793: "https://open.spotify.com/track/7cqhNtmZgpE2mS9imqlO09", // 世界は可愛く出来ている (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    68794: "https://open.spotify.com/track/7ycLKHCH42BrvtC5OLeA3f", // 魔獣スクランブル (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74739: "https://open.spotify.com/track/2hV5gdekWA7HYs31pgziTw", // 鬼は悠久の山に (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74740: "https://open.spotify.com/track/3kt6VGEhCR0P5OHzYI7y9Q", // タイニーシャングリラ (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74741: "https://open.spotify.com/track/2uzuz6xTqAU9sSpGStOU4Y", // 勇敢で有閑な妖獣 (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74742: "https://open.spotify.com/track/25Dw8C9UdRVdgZROZyT2wH", // 吸血怪獣チュパカブラ (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74743: "https://open.spotify.com/track/3qvZReqvXo1tWv3UzDZZZO", // 振り向かない黄泉の道 (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74744: "https://open.spotify.com/track/4kZppGEv35YlZddiObY6oq", // 逸脱者達の無礙光　〜 Kingdam of Nothingness. (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74745: "https://open.spotify.com/track/1pdiOllymN1a7QZwCR2q3R", // 少女が見た日本の原風景 (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74746: "https://open.spotify.com/track/0vUToLd6CC0YY0vD9hqbWH", // 妖々跋扈　〜 Who done it! (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    68795: "https://open.spotify.com/track/1sE9ge7VtO0lUyKqtEW07j", // 一対の神獣 (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    68796: "https://open.spotify.com/track/6QOyWbVVI0DwQbL3k8AeZm", // 春の湊に (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    68797: "https://open.spotify.com/track/4HHMphBqnpt50I6KwwTMzY", // 忘れがたき、よすがの緑 (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74747: "https://open.spotify.com/track/5HoAyJbAdcP7DPbhVEqVwD", // 死体旅行　〜 Be of good cheer! (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74748: "https://open.spotify.com/track/0K4XGpE8Q4GF64Lww1Pxis", // 待ちわびた逢魔が時 (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74749: "https://open.spotify.com/track/0OyfYQIgsRm0LnMTYFC5tm", // 佐渡の二ッ岩 (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74750: "https://open.spotify.com/track/4TxKoJR8ddorSGrX0cPswG", // トータスドラゴン　〜 幸運と不運 (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74751: "https://open.spotify.com/track/2y0ZAdGVvXNQBHEyv8mHXu", // 聖徳太子のペガサス　〜 Dark Pegasus (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74752: "https://open.spotify.com/track/3GEkMt1pwfcT31wMY4VMmX", // 強欲な獣のメメント (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74753: "https://open.spotify.com/track/2VGrGzSOWLpY2y0c04a6iZ", // 獣王達の休息 (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    74754: "https://open.spotify.com/track/0TAvl40aO9oe4yschuvxqN", // 獣に知性はあるか (東方獣王園　〜 Unfinished Dream of All Living Ghost)
    95732: "https://open.spotify.com/track/6mruE9DguB0slGnxVMfwvx", // 七夕坂に朝が来る (七夕坂夢幻能 〜 Taboo Japan Disentanglement.)
    95733: "https://open.spotify.com/track/6qo9aBLaKaI77itBgCeaM0", // 不等式のティンカーベル (七夕坂夢幻能 〜 Taboo Japan Disentanglement.)
    95734: "https://open.spotify.com/track/0bbcb9HOrAldjg3u6IbvgX", // 禁断の扉の向こうは、この世かあの世か (七夕坂夢幻能 〜 Taboo Japan Disentanglement.)
    95735: "https://open.spotify.com/track/1noXAjEB50vokOs4jSTiy0", // スモーキングドラゴン (七夕坂夢幻能 〜 Taboo Japan Disentanglement.)
    95736: "https://open.spotify.com/track/4nmXbBFfUBVJm5J4u9odHj", // 夢幻能　〜 Taboo Marionette (七夕坂夢幻能 〜 Taboo Japan Disentanglement.)
    95737: "https://open.spotify.com/track/06EwxTLErZZf58WVwj9Qm8", // クレイジーバックダンサーズ (七夕坂夢幻能 〜 Taboo Japan Disentanglement.)
    95738: "https://open.spotify.com/track/0Y8bGWvpusDiHith9eoiFU", // 憑坐は夢と現の間に　〜 Necro-Fantasia (七夕坂夢幻能 〜 Taboo Japan Disentanglement.)
    95739: "https://open.spotify.com/track/775ZDUGtiJOvw4BZyPRwbU", // ひとりぼっちの常陸行路 (七夕坂夢幻能 〜 Taboo Japan Disentanglement.)
    95740: "https://open.spotify.com/track/5lkdr2fMH64gI6mt3tyBL4", // 地蔵だけが知る哀嘆 (七夕坂夢幻能 〜 Taboo Japan Disentanglement.)
    95741: "https://open.spotify.com/track/4OSF7b1NyqVpFtWcXSxutR", // 秘匿されたフォーシーズンズ (七夕坂夢幻能 〜 Taboo Japan Disentanglement.)
    95742: "https://open.spotify.com/track/5tQdf0RqFQxzi0M4DC8RwB", // 夜じゃなくてもお化けはいるから (七夕坂夢幻能 〜 Taboo Japan Disentanglement.)
};
